[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app -b 0.0.0.0:${PORT}"